const PRODUCT_ROWS=[
['domates','Bahçe Domatesi','Sebze','🍅','Kahramanmaraş / Dulkadiroğlu','Bereket Çiftliği','Aynı gün hasat',17.44,'HKS'],
['kapya_biber','Kapya Biber','Sebze','🌶️','Gaziantep / Oğuzeli','Güneş Tarım','Dalından toplama',24.59,'HKS'],
['sivri_biber','Sivri Biber','Sebze','🌶️','Antalya / Kumluca','Akdeniz Sera','Sabah hasadı',23.20,'Pilot referans'],
['salatalik','Salatalık','Sebze','🥒','Mersin / Erdemli','Sahil Sera','Seradan günlük',16.90,'Pilot referans'],
['patlican','Patlıcan','Sebze','🍆','Hatay / Arsuz','Mor Tarla','Aynı gün toplama',21.40,'Pilot referans'],
['kabak','Kabak','Sebze','🥒','Sakarya / Geyve','Yeşil Vadi','Günlük hasat',18.30,'Pilot referans'],
['patates','Patates','Sebze','🥔','Niğde / Bor','Ova Tarım','Yeni söküm',14.80,'Pilot referans'],
['sogan','Kuru Soğan','Sebze','🧅','Amasya / Suluova','Ova Üretim','Yeni hasat',13.60,'Pilot referans'],
['havuc','Havuç','Sebze','🥕','Konya / Kaşınhanı','Toprak Bahçesi','Yeni söküm',17.20,'Pilot referans'],
['marul','Marul','Sebze','🥬','Ankara / Ayaş','Ayaş Bahçesi','Sabah kesimi',19.50,'Pilot referans'],
['ispanak','Ispanak','Sebze','🥬','İzmir / Menemen','Gediz Tarım','Günlük kesim',22.10,'Pilot referans'],
['brokoli','Brokoli','Sebze','🥦','Bursa / Karacabey','Marmara Tarım','Taze kesim',29.40,'Pilot referans'],
['karnabahar','Karnabahar','Sebze','🥦','Bursa / Mustafakemalpaşa','Beyaz Ova','Taze kesim',25.80,'Pilot referans'],
['fasulye_taze','Taze Fasulye','Sebze','🫛','Samsun / Bafra','Kızılırmak Tarım','Günlük toplama',34.20,'Pilot referans'],
['bezelye','Bezelye','Sebze','🫛','Balıkesir / Gönen','Gönen Bahçesi','Yeni toplama',31.70,'Pilot referans'],
['sarimsak','Sarımsak','Sebze','🧄','Kastamonu / Taşköprü','Taşköprü Üretici','Yeni sezon',82.00,'Pilot referans'],
['elma','Elma','Meyve','🍎','Niğde / Bor','Yayla Bahçesi','Yakın teslim',26.18,'HKS'],
['armut','Armut','Meyve','🍐','Bursa / Gürsu','Uludağ Bahçesi','Yeni sezon',32.60,'Pilot referans'],
['portakal','Portakal','Meyve','🍊','Adana / Kozan','Çukurova Bahçesi','Dalından',24.40,'Pilot referans'],
['mandalina','Mandalina','Meyve','🍊','İzmir / Seferihisar','Ege Narenciye','Dalından',23.80,'Pilot referans'],
['limon','Limon','Meyve','🍋','Mersin / Erdemli','Limon Vadisi','Yeni kesim',27.20,'Pilot referans'],
['cilek','Çilek','Meyve','🍓','Aydın / Sultanhisar','Kırmızı Vadi','Aynı gün toplama',58.40,'Pilot referans'],
['uzum','Sofralık Üzüm','Meyve','🍇','Manisa / Alaşehir','Asma Vadisi','Bağdan günlük',39.80,'Pilot referans'],
['kiraz','Kiraz','Meyve','🍒','İzmir / Kemalpaşa','Kiraz Bahçesi','Günlük toplama',72.00,'Pilot referans'],
['seftali','Şeftali','Meyve','🍑','Bursa / İnegöl','Şeftali Ovası','Dalından',38.20,'Pilot referans'],
['kayisi','Kayısı','Meyve','🍑','Malatya / Battalgazi','Kayısı Bahçesi','Yeni toplama',46.00,'Pilot referans'],
['erik','Erik','Meyve','🟢','Mersin / Mut','Mut Bahçesi','Günlük toplama',41.50,'Pilot referans'],
['nar','Nar','Meyve','🔴','Antalya / Gazipaşa','Nar Vadisi','Yeni sezon',30.80,'Pilot referans'],
['karpuz','Karpuz','Meyve','🍉','Diyarbakır / Sur','Dicle Ovası','Tarladan günlük',12.40,'Pilot referans'],
['kavun','Kavun','Meyve','🍈','Manisa / Kırkağaç','Kırkağaç Üretici','Tarladan günlük',17.90,'Pilot referans'],
['muz','Muz','Meyve','🍌','Mersin / Anamur','Anamur Muz','Seradan günlük',44.00,'Pilot referans'],
['incir','İncir','Meyve','🟣','Aydın / Germencik','İncir Bahçesi','Yeni toplama',53.00,'Pilot referans'],
['bugday','Buğday','Tahıl','🌾','Konya / Cihanbeyli','Anadolu Tahıl','Yeni mahsul',13.20,'Pilot referans'],
['arpa','Arpa','Tahıl','🌾','Konya / Altınekin','Bozkır Tahıl','Yeni mahsul',11.80,'Pilot referans'],
['misir','Mısır','Tahıl','🌽','Adana / Ceyhan','Çukurova Tahıl','Yeni mahsul',12.50,'Pilot referans'],
['pirinc','Pirinç / Çeltik','Tahıl','🍚','Edirne / İpsala','Meriç Üretici','Yeni mahsul',42.00,'Pilot referans'],
['yulaf','Yulaf','Tahıl','🌾','Eskişehir / Sivrihisar','Bozkır Tarım','Yeni mahsul',15.70,'Pilot referans'],
['cavdar','Çavdar','Tahıl','🌾','Ankara / Polatlı','Polatlı Tahıl','Yeni mahsul',14.10,'Pilot referans'],
['nohut','Nohut','Bakliyat','🫘','Kırşehir / Mucur','Bozkır Bakliyat','Yeni mahsul',48.00,'Pilot referans'],
['mercimek','Kırmızı Mercimek','Bakliyat','🫘','Şanlıurfa / Viranşehir','Harran Bakliyat','Yeni mahsul',46.50,'Pilot referans'],
['fasulye_kuru','Kuru Fasulye','Bakliyat','🫘','Konya / Beyşehir','Göl Ovası','Yeni mahsul',56.00,'Pilot referans'],
['barbunya','Barbunya','Bakliyat','🫘','Balıkesir / Manyas','Manyas Üretici','Yeni mahsul',62.00,'Pilot referans'],
['bulgur','Bulgur','Bakliyat','🌾','Gaziantep / Nizip','Antep Tahıl','Yeni üretim',31.00,'Pilot referans'],
['bal','Doğal Bal','Doğal Ürün','🍯','Kahramanmaraş / Andırın','Dağ Arıcılığı','Doğrudan üreticiden',294.00,'Pilot referans'],
['ceviz','Ceviz','Doğal Ürün','🌰','Malatya / Akçadağ','Anadolu Bahçesi','Yeni sezon',280.00,'TOBB'],
['badem','Badem','Doğal Ürün','🌰','Mersin / Mut','Toros Badem','Yeni sezon',205.00,'Pilot referans'],
['findik','Fındık','Doğal Ürün','🌰','Ordu / Fatsa','Karadeniz Bahçesi','Yeni sezon',188.00,'Pilot referans'],
['zeytin','Sofralık Zeytin','Doğal Ürün','🫒','Manisa / Akhisar','Akhisar Zeytin','Yeni mahsul',96.00,'Pilot referans']
];
const palette={'Sebze':['#0d5f3a','#52b86b','#8be3a0'],'Meyve':['#7d2734','#d85a55','#ffb56e'],'Tahıl':['#75531f','#c69b48','#f2d27d'],'Bakliyat':['#593b24','#9b6e48','#d7aa78'],'Doğal Ürün':['#4d3c16','#9f7d2d','#e6c45b']};
const PRODUCTS=PRODUCT_ROWS.map(r=>({id:r[0],name:r[1],category:r[2],emoji:r[3],location:r[4],farm:r[5],fresh:r[6],reference:r[7],source:r[8]}));
const STATE={category:'all',active:'domates',qty:5,cart:[],payment:false,order:null,projectPane:'intro',livePane:'map',map:null,poly:null,marker:null,timer:null};
const fmt=n=>new Intl.NumberFormat('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n),sale=p=>p.reference*1.05/0.80,payout=p=>p.reference*1.05,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function visualFor(p,w=520,h=300){const c=palette[p.category]||palette.Sebze;const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><defs><linearGradient id="sky" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#8fd7ff"/><stop offset="1" stop-color="#dff6ff"/></linearGradient><linearGradient id="field" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${c[1]}"/><stop offset="1" stop-color="${c[0]}"/></linearGradient></defs><rect width="${w}" height="${h}" fill="url(#sky)"/><circle cx="${w*.82}" cy="${h*.20}" r="${h*.10}" fill="#ffe18a"/><path d="M0 ${h*.54} Q ${w*.25} ${h*.34} ${w*.52} ${h*.52} T ${w} ${h*.48} V${h} H0Z" fill="${c[2]}" opacity=".85"/><path d="M0 ${h*.66} Q ${w*.35} ${h*.48} ${w*.64} ${h*.64} T ${w} ${h*.58} V${h} H0Z" fill="url(#field)"/><text x="50%" y="59%" text-anchor="middle" font-size="${Math.min(w,h)*.28}" font-family="Apple Color Emoji,Segoe UI Emoji,Noto Color Emoji,sans-serif">${p.emoji}</text><rect x="18" y="18" rx="14" width="${Math.min(w*.42,190)}" height="34" fill="rgba(4,17,27,.62)"/><text x="34" y="40" fill="#eafff0" font-size="14" font-weight="700" font-family="Arial">${esc(p.category)}</text><rect x="0" y="${h-62}" width="${w}" height="62" fill="rgba(4,17,27,.64)"/><text x="22" y="${h-34}" fill="#fff" font-size="22" font-weight="800" font-family="Arial">${esc(p.name)}</text><text x="22" y="${h-13}" fill="#aeecc1" font-size="12" font-family="Arial">${esc(p.farm)}</text></svg>`;return'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg)}
function getActive(){return PRODUCTS.find(p=>p.id===STATE.active)||PRODUCTS[0]}function filtered(){return STATE.category==='all'?PRODUCTS:PRODUCTS.filter(p=>p.category===STATE.category)}
async function loadPrices(){try{const r=await fetch('data/prices.json',{cache:'no-store'});if(!r.ok)throw 0;const d=await r.json(),map=d.products||{};let count=0;Object.entries(map).forEach(([id,row])=>{const p=PRODUCTS.find(x=>x.id===id);if(p&&Number(row.official_avg)){p.reference=Number(row.official_avg);p.source=(row.source||'').toLowerCase()==='hks'?'HKS':(row.source||'').toLowerCase()==='tobb'?'TOBB':row.source_name||p.source;count++}});$('#priceFeedStatus').textContent=`HKS ✓ • TOBB ✓ • ${count} resmi eşleşme`}catch(e){$('#priceFeedStatus').textContent='HKS / TOBB hazır • pilot referanslar açık'}renderMarket();renderCart()}
function renderMarket(){$$('#categoryTabs .chip').forEach(b=>b.classList.toggle('active',b.dataset.category===STATE.category));const list=filtered();$('#pickerCount').textContent=`${list.length} ürün`;const wrap=$('#productPicker');wrap.innerHTML='';list.forEach(p=>{const b=document.createElement('button');b.className='pick-card'+(p.id===STATE.active?' active':'');b.innerHTML=`<img class="pick-img" src="${visualFor(p,180,120)}" alt="${esc(p.name)}"><span><b>${esc(p.name)}</b><small>${esc(p.location.split('/')[0].trim())} • ${esc(p.source)}</small><strong>${fmt(sale(p))} ₺/kg</strong></span>`;b.onclick=()=>{STATE.active=p.id;renderMarket()};wrap.appendChild(b)});const p=getActive();$('#detailVisual').src=visualFor(p,760,440);$('#detailVisual').alt=p.name;$('#detailFarm').textContent=p.farm;$('#detailName').textContent=p.name;$('#detailLocation').textContent=p.location;$('#detailPrice').textContent=`${fmt(sale(p))} ₺/kg`;$('#detailPayout').textContent=`${fmt(payout(p))} ₺/kg`;$('#detailSource').textContent=p.source;$('#detailFresh').textContent=p.fresh;$('#qtyValue').textContent=`${STATE.qty} kg`}
function renderCart(){const list=$('#cartList');list.innerHTML='';if(!STATE.cart.length)list.innerHTML='<div class="empty-state"><b>Sepet boş</b><small>Pazar ekranından bir ürün seçip sepete ekleyin.</small></div>';STATE.cart.forEach(item=>{const p=PRODUCTS.find(x=>x.id===item.id),row=document.createElement('div');row.className='cart-item';row.innerHTML=`<img class="cart-img" src="${visualFor(p,140,100)}" alt="${esc(p.name)}"><div><b>${esc(p.name)}</b><small>${esc(p.farm)} • ${esc(p.location)}</small><strong>${fmt(sale(p)*item.qty)} ₺</strong></div><div class="cart-qty"><button data-act="minus">−</button><b>${item.qty} kg</b><button data-act="plus">+</button><button class="remove" data-act="remove">×</button></div>`;row.querySelector('[data-act=minus]').onclick=()=>changeCart(p.id,-1);row.querySelector('[data-act=plus]').onclick=()=>changeCart(p.id,1);row.querySelector('[data-act=remove]').onclick=()=>removeCart(p.id);list.appendChild(row)});const total=STATE.cart.reduce((s,i)=>{const p=PRODUCTS.find(x=>x.id===i.id);return s+sale(p)*i.qty},0),count=STATE.cart.reduce((s,i)=>s+i.qty,0);$('#cartTotal').textContent=`${fmt(total)} ₺`;$('#cartCount').textContent=count;$('#cartCountTop').textContent=`${STATE.cart.length} ürün`;$('#createPayment').disabled=!STATE.cart.length;$('#startPaidOrder').disabled=!STATE.payment||!STATE.cart.length;$('#paymentState').innerHTML=STATE.payment?'<span>ÖDEME DURUMU</span><b>Güvenli ödeme kaydı oluşturuldu</b><small>MVP ödeme kaydı hazır. Gerçek ödeme kuruluşu bağlandığında bu adım gerçek tahsilat / bekletme akışına geçecek.</small>':'<span>ÖDEME DURUMU</span><b>Henüz oluşturulmadı</b><small>Bu MVP gerçek kart bilgisi toplamaz; gerçek ödeme kuruluşu entegrasyonu bağlanana kadar güvenli ödeme pilot kaydı olarak çalışır.</small>'}
function changeCart(id,d){const i=STATE.cart.find(x=>x.id===id);if(!i)return;i.qty=Math.max(1,i.qty+d);STATE.payment=false;renderCart()}function removeCart(id){STATE.cart=STATE.cart.filter(x=>x.id!==id);STATE.payment=false;renderCart()}function addCart(){const p=getActive();let i=STATE.cart.find(x=>x.id===p.id);if(i)i.qty+=STATE.qty;else STATE.cart.push({id:p.id,qty:STATE.qty});STATE.payment=false;renderCart();flashStatus(`${p.name} sepete eklendi`)}
const STAGES=[['Sipariş oluşturuldu','Güvenli ödeme kaydı ile sipariş operasyon merkezine düştü.'],['Çiftçi bildirimi','Ürün ve kg bilgisi çiftçinin telefonuna iletildi.'],['YZ planlama','Fiyat, rota ve drone görevi tek sipariş kimliğinde oluşturuldu.'],['Hasat','Çiftçi sipariş miktarını bahçeden topluyor.'],['Foto onay','Toplanan ürünler vatandaşa görsel onay için gönderildi.'],['Drone yükleme','Paket güvenli drone bölmesine yerleştirildi.'],['Kalkış + ödeme','Drone kalktı; üretici hakedişi serbest bırakıldı.'],['Teslimat + dönüş','Teslimat tamamlandı; drone merkeze dönüyor.']];
function createPayment(){if(!STATE.cart.length)return;STATE.payment=true;renderCart();flashStatus('Güvenli ödeme kaydı hazır')}function startOrder(){if(!STATE.payment||!STATE.cart.length)return;const first=PRODUCTS.find(x=>x.id===STATE.cart[0].id);STATE.order={code:`TT-${Date.now().toString().slice(-6)}`,stage:0,first,items:STATE.cart.map(x=>({...x})),created:Date.now()};renderOrder();renderOps();switchView('order');if(STATE.timer)clearInterval(STATE.timer);STATE.timer=setInterval(()=>{if(!STATE.order)return;if(STATE.order.stage<7){STATE.order.stage++;renderOrder();renderOps();updateTelemetry()}else{clearInterval(STATE.timer);STATE.timer=null}},6500)}
function renderOrder(){const o=STATE.order,grid=$('#stageGrid');grid.innerHTML='';STAGES.forEach((s,i)=>{const d=document.createElement('div');d.className='stage-dot'+(o?(i<o.stage?' done':i===o.stage?' active':''):'');d.innerHTML=`<span>${i+1}</span><small>${s[0]}</small>`;grid.appendChild(d)});if(!o){$('#orderTitle').textContent='Henüz sipariş yok';$('#orderCode').textContent='—';$('#orderProduct').textContent='Ürün seçilmedi';$('#orderSummary').textContent='Sepetten güvenli ödeme oluşturup siparişi başlatın.';$('#orderThumb').removeAttribute('src');$('#orderProgress').style.width='0%';$('#nowTitle').textContent='Sipariş bekleniyor';$('#nowText').textContent='Ödeme kaydı oluşturulduktan sonra bütün süreç burada canlı ilerler.';return}const totalQty=o.items.reduce((s,i)=>s+i.qty,0);$('#orderTitle').textContent=`${totalQty} kg sipariş ilerliyor`;$('#orderCode').textContent=o.code;$('#orderProduct').textContent=o.items.length===1?o.first.name:`${o.items.length} farklı ürün`;$('#orderSummary').textContent=`${totalQty} kg • ${o.first.farm} başlangıç noktası`;$('#orderThumb').src=visualFor(o.first,120,120);$('#orderProgress').style.width=`${((o.stage+1)/8)*100}%`;$('#nowTitle').textContent=STAGES[o.stage][0];$('#nowText').textContent=STAGES[o.stage][1]}
function renderOps(){const o=STATE.order;$('#opsOrderCount').textContent=o?'1':'0';$('#opsOrderState').textContent=o?STAGES[o.stage][0]:'Beklemede';$('#opsDroneState').textContent=o?(o.stage>=6?(o.stage===7?'Dönüşte':'Uçuşta'):'Hazır'):'Hazır';$('#opsDroneDetail').textContent=o?`${o.code} • ${o.first.location.split('/')[0].trim()}`:'TT-D01 • merkez';$('#opsPayoutState').textContent=o&&o.stage>=6?'Serbest bırakıldı':'Beklemede';const t=$('#opsTimeline');t.innerHTML='';const upto=o?o.stage:0;(o?STAGES.slice(0,upto+1):[['Hazır sistem','Yeni sipariş bekleniyor.']]).forEach((s,i)=>{const e=document.createElement('div');e.className='ops-event';e.innerHTML=`<time>${o?(i===upto?'Şimdi':`${(upto-i)*2} dk önce`):'Hazır'}</time><div><b>${s[0]}</b><small>${s[1]}</small></div>`;t.appendChild(e)})}
function switchView(v){$$('.app-view').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$$('.bottom-nav button').forEach(x=>x.classList.toggle('active',x.dataset.nav===v));if(v==='live')setTimeout(()=>{initMap();updateMap();updateTelemetry()},80)}function switchProjectPane(pane){STATE.projectPane=pane;$$('.project-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.projectPane===pane));$$('.project-pane').forEach(p=>p.classList.toggle('active',p.dataset.projectContent===pane));if(pane==='ops')renderOps()}
function initMap(){if(STATE.map||typeof L==='undefined')return;STATE.map=L.map('routeMap',{zoomControl:false}).setView([37.58,36.94],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(STATE.map);STATE.poly=L.polyline([],{color:'#45dc86',weight:4,opacity:.9}).addTo(STATE.map);const icon=L.divIcon({className:'',html:'<div class="drone-dot">✈</div>',iconSize:[30,30],iconAnchor:[15,15]});STATE.marker=L.marker([37.58,36.94],{icon}).addTo(STATE.map)}function routePoints(){const p=STATE.order?.first||getActive(),seed=[...p.id].reduce((s,c)=>s+c.charCodeAt(0),0),base=[37.575+(seed%23)*.001,36.92+(seed%17)*.001];return[[base[0],base[1]],[base[0]+.024,base[1]+.018],[base[0]+.009,base[1]-.015],[base[0],base[1]]]}function updateMap(){if(!STATE.map)return;const pts=routePoints();STATE.poly.setLatLngs(pts);STATE.map.fitBounds(pts,{padding:[22,22]});const stage=STATE.order?.stage??0;let pos=pts[0];if(stage>=3&&stage<=5)pos=pts[1];else if(stage===6)pos=[(pts[1][0]+pts[2][0])/2,(pts[1][1]+pts[2][1])/2];else if(stage>=7)pos=[(pts[2][0]+pts[3][0])/2,(pts[2][1]+pts[3][1])/2];STATE.marker.setLatLng(pos)}
function updateTelemetry(){if(STATE.map)updateMap();const s=STATE.order?.stage??-1;let alt=0,spd=0,bat=100,eta='—',title='Rota bekleniyor',text='Sipariş verildiğinde operasyon merkezi rotayı burada gösterecek.';if(s>=0){eta=s<7?`${Math.max(2,16-s*2)} dk`:'Teslim edildi';if(s<5){title=STAGES[s][0];text=STAGES[s][1]}else if(s===5){alt=4;bat=94;title='Drone yükleme alanında';text='Paket kilitleniyor, kalkış için son kontrol yapılıyor.'}else if(s===6){alt=64;spd=41;bat=79;title='Drone teslimat rotasında';text='Vatandaş teslimatını harita ve kamera üzerinden izleyebilir.'}else{alt=56;spd=36;bat=65;title='Drone merkeze dönüyor';text='Teslimat tamamlandı, drone otonom dönüşte.'}}$('#mapDroneId').textContent=STATE.order?.code||'TT-D01';$('#mapEta').textContent=eta;$('#altitude').textContent=`${alt} m`;$('#speed').textContent=`${spd} km/sa`;$('#battery').textContent=`${bat}%`;$('#distance').textContent=s>=6?'2,4 km':'—';$('#routeStatusTitle').textContent=title;$('#routeStatusText').textContent=text;$('#routeStatusDot').classList.toggle('on',s>=0);$('#camAlt').textContent=`${alt} m`;$('#camSpeed').textContent=`${spd} km/sa`;$('#camGps').textContent=routePoints()[0].map(x=>x.toFixed(4)).join(', ');$('#cameraTitle').textContent=title;$('#cameraText').textContent=text+' Gerçek drone video URL’si bağlandığında bu saha görünümü canlı yayınla değişir.'}
function flashStatus(msg){$('#systemStatus').textContent=msg;setTimeout(()=>$('#systemStatus').textContent=STATE.order?STAGES[STATE.order.stage][0]:'Sistem hazır',1800)}function bind(){$$('#categoryTabs .chip').forEach(b=>b.onclick=()=>{STATE.category=b.dataset.category;const f=filtered();if(!f.some(p=>p.id===STATE.active))STATE.active=f[0]?.id||'domates';renderMarket()});$('#qtyMinus').onclick=()=>{STATE.qty=Math.max(1,STATE.qty-1);$('#qtyValue').textContent=`${STATE.qty} kg`};$('#qtyPlus').onclick=()=>{STATE.qty=Math.min(50,STATE.qty+1);$('#qtyValue').textContent=`${STATE.qty} kg`};$('#addCart').onclick=addCart;$('#createPayment').onclick=createPayment;$('#startPaidOrder').onclick=startOrder;$('#openLiveFromOrder').onclick=()=>switchView('live');$('#refreshPrices').onclick=loadPrices;$$('.bottom-nav button').forEach(b=>b.onclick=()=>switchView(b.dataset.nav));$$('.project-tabs button').forEach(b=>b.onclick=()=>switchProjectPane(b.dataset.projectPane));$$('[data-open-role]').forEach(b=>b.onclick=()=>switchProjectPane(b.dataset.openRole));$$('.live-tabs button').forEach(b=>b.onclick=()=>{STATE.livePane=b.dataset.livePane;$$('.live-tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.live-pane').forEach(x=>x.classList.toggle('active',x.dataset.liveContent===STATE.livePane));if(STATE.livePane==='map')setTimeout(()=>{initMap();updateMap()},60)});setInterval(()=>$('#camTime').textContent=new Date().toLocaleTimeString('tr-TR'),1000)}
function boot(){bind();renderMarket();renderCart();renderOrder();renderOps();switchProjectPane('intro');loadPrices()}document.addEventListener('DOMContentLoaded',boot);