const PRODUCT_ROWS=[
['domates','Bahçe Domatesi','Sebze','🍅','Kahramanmaraş / Dulkadiroğlu','Bereket Çiftliği','Aynı gün hasat',17.44],
['kapya_biber','Kapya Biber','Sebze','🌶️','Gaziantep / Oğuzeli','Güneş Tarım','Dalından toplama',24.59],
['sivri_biber','Sivri Biber','Sebze','🌶️','Antalya / Kumluca','Akdeniz Sera','Sabah hasadı',23.20],
['salatalik','Salatalık','Sebze','🥒','Mersin / Erdemli','Sahil Sera','Seradan günlük',16.90],
['patlican','Patlıcan','Sebze','🍆','Hatay / Arsuz','Mor Tarla','Aynı gün toplama',21.40],
['kabak','Kabak','Sebze','🥒','Sakarya / Geyve','Yeşil Vadi','Günlük hasat',18.30],
['patates','Patates','Sebze','🥔','Niğde / Bor','Ova Tarım','Yeni söküm',14.80],
['sogan','Kuru Soğan','Sebze','🧅','Amasya / Suluova','Ova Üretim','Yeni hasat',13.60],
['havuc','Havuç','Sebze','🥕','Konya / Kaşınhanı','Toprak Bahçesi','Yeni söküm',17.20],
['marul','Marul','Sebze','🥬','Ankara / Ayaş','Ayaş Bahçesi','Sabah kesimi',19.50],
['ispanak','Ispanak','Sebze','🥬','İzmir / Menemen','Gediz Tarım','Günlük kesim',22.10],
['brokoli','Brokoli','Sebze','🥦','Bursa / Karacabey','Marmara Tarım','Taze kesim',29.40],
['karnabahar','Karnabahar','Sebze','🥦','Bursa / Mustafakemalpaşa','Beyaz Ova','Taze kesim',25.80],
['fasulye_taze','Taze Fasulye','Sebze','🫛','Samsun / Bafra','Kızılırmak Tarım','Günlük toplama',34.20],
['bezelye','Bezelye','Sebze','🫛','Balıkesir / Gönen','Gönen Bahçesi','Yeni toplama',31.70],
['sarimsak','Sarımsak','Sebze','🧄','Kastamonu / Taşköprü','Taşköprü Üretici','Yeni sezon',82.00],
['elma','Elma','Meyve','🍎','Niğde / Bor','Yayla Bahçesi','Yakın teslim',26.18],
['armut','Armut','Meyve','🍐','Bursa / Gürsu','Uludağ Bahçesi','Yeni sezon',32.60],
['portakal','Portakal','Meyve','🍊','Adana / Kozan','Çukurova Bahçesi','Dalından',24.40],
['mandalina','Mandalina','Meyve','🍊','İzmir / Seferihisar','Ege Narenciye','Dalından',23.80],
['limon','Limon','Meyve','🍋','Mersin / Erdemli','Limon Vadisi','Yeni kesim',27.20],
['cilek','Çilek','Meyve','🍓','Aydın / Sultanhisar','Kırmızı Vadi','Aynı gün toplama',58.40],
['uzum','Sofralık Üzüm','Meyve','🍇','Manisa / Alaşehir','Asma Vadisi','Bağdan günlük',39.80],
['kiraz','Kiraz','Meyve','🍒','İzmir / Kemalpaşa','Kiraz Bahçesi','Günlük toplama',72.00],
['seftali','Şeftali','Meyve','🍑','Bursa / İnegöl','Şeftali Ovası','Dalından',38.20],
['kayisi','Kayısı','Meyve','🍑','Malatya / Battalgazi','Kayısı Bahçesi','Yeni toplama',46.00],
['erik','Erik','Meyve','🟢','Mersin / Mut','Mut Bahçesi','Günlük toplama',41.50],
['nar','Nar','Meyve','🔴','Antalya / Gazipaşa','Nar Vadisi','Yeni sezon',30.80],
['karpuz','Karpuz','Meyve','🍉','Diyarbakır / Sur','Dicle Ovası','Tarladan günlük',12.40],
['kavun','Kavun','Meyve','🍈','Manisa / Kırkağaç','Kırkağaç Üretici','Tarladan günlük',17.90],
['muz','Muz','Meyve','🍌','Mersin / Anamur','Anamur Muz','Seradan günlük',44.00],
['incir','İncir','Meyve','🟣','Aydın / Germencik','İncir Bahçesi','Yeni toplama',53.00],
['bugday','Buğday','Tahıl','🌾','Konya / Cihanbeyli','Anadolu Tahıl','Yeni mahsul',13.20],
['arpa','Arpa','Tahıl','🌾','Konya / Altınekin','Bozkır Tahıl','Yeni mahsul',11.80],
['misir','Mısır','Tahıl','🌽','Adana / Ceyhan','Çukurova Tahıl','Yeni mahsul',12.50],
['pirinc','Pirinç / Çeltik','Tahıl','🍚','Edirne / İpsala','Meriç Üretici','Yeni mahsul',42.00],
['yulaf','Yulaf','Tahıl','🌾','Eskişehir / Sivrihisar','Bozkır Tarım','Yeni mahsul',15.70],
['cavdar','Çavdar','Tahıl','🌾','Ankara / Polatlı','Polatlı Tahıl','Yeni mahsul',14.10],
['nohut','Nohut','Bakliyat','🫘','Kırşehir / Mucur','Bozkır Bakliyat','Yeni mahsul',48.00],
['mercimek','Kırmızı Mercimek','Bakliyat','🫘','Şanlıurfa / Viranşehir','Güneydoğu Bakliyat','Yeni mahsul',45.00],
['kuru_fasulye','Kuru Fasulye','Bakliyat','🫘','Niğde / Çiftlik','Ova Bakliyat','Yeni mahsul',61.00],
['barbunya','Barbunya','Bakliyat','🫘','Bursa / Karacabey','Marmara Bakliyat','Yeni mahsul',68.00],
['bakla','Kuru Bakla','Bakliyat','🫘','Balıkesir / Bandırma','Güney Marmara','Yeni mahsul',39.00],
['yesil_mercimek','Yeşil Mercimek','Bakliyat','🫘','Yozgat / Sorgun','Bozok Üretici','Yeni mahsul',52.00],
['ceviz','Ceviz','Doğal Ürün','🌰','Malatya / Akçadağ','Anadolu Bahçesi','Yeni sezon',280.00],
['bal','Doğal Bal','Doğal Ürün','🍯','Kahramanmaraş / Andırın','Dağ Arıcılığı','Doğrudan üreticiden',330.00],
['badem','Badem','Doğal Ürün','🌰','Muğla / Datça','Datça Bahçesi','Yeni sezon',210.00],
['findik','Fındık','Doğal Ürün','🌰','Ordu / Altınordu','Karadeniz Bahçesi','Yeni sezon',165.00]
];
const POS={
Kahramanmaraş:[[37.5758,36.9226],[37.5854,36.9342],[37.5888,36.9416]],Gaziantep:[[37.0637,37.3824],[37.0702,37.3890],[37.0765,37.3950]],Niğde:[[37.8897,34.5587],[37.8950,34.5660],[37.9010,34.5740]],Malatya:[[38.3456,37.9677],[38.3510,37.9750],[38.3570,37.9830]],Mersin:[[36.6115,34.3120],[36.6180,34.3210],[36.6260,34.3290]],Konya:[[37.8746,32.4932],[37.8810,32.5020],[37.8880,32.5100]],Adana:[[37.0000,35.3213],[37.0060,35.3290],[37.0120,35.3370]],Bursa:[[40.1950,29.0600],[40.2010,29.0690],[40.2070,29.0770]],default:[[39.9255,32.8663],[39.9310,32.8750],[39.9370,32.8840]]};
const PRODUCTS=PRODUCT_ROWS.map((r,i)=>{const city=r[4].split('/')[0].trim(),pos=POS[city]||POS.default;return {key:r[0],name:r[1],cat:r[2],emoji:r[3],location:r[4],farmer:r[5],fresh:r[6],pilotRef:r[7],stock:`${120+(i*17)%330} kg`,farm:pos[0],center:pos[1],delivery:pos[2]}});
const POLICY={platformShare:0.20,farmerUplift:0.05};
const STAGES=[['Sipariş','Güvenli ödeme kaydıyla sipariş oluşturuldu','▣'],['Çiftçi','Üretici telefonuna görev gönderildi','⌕'],['Hasat','Ürünler siparişe göre hazırlanıyor','✦'],['Onay','Fotoğraf kontrolü tamamlanıyor','✓'],['Drone','Drone üretici noktasına yönlendirildi','⌁'],['Teslim','Paket teslim istasyonuna taşınıyor','⌖'],['Ödeme','Kalkış doğrulandı, üretici hakedişi serbest','₺'],['Dönüş','Drone merkeze dönüyor','↺']];
let selected=0,qty=5,category='all',priceData=null,cart=[],payment=null,activeOrder=null,stageTimer=null,stageIndex=0,map=null,droneMarker=null,routeLine=null,routeTimer=null,routeProgress=0;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function money(v){return Number.isFinite(v)?`${v.toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2})} ₺`:'Veri bekleniyor'}
function kgMoney(v){return Number.isFinite(v)?`${v.toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2})} ₺/kg`:'Veri bekleniyor'}
function nowTime(){return new Date().toLocaleTimeString('tr-TR',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}
function currentProduct(){return PRODUCTS[selected]}
function feedRow(p){return priceData?.products?.[p.key]||null}
function official(p){const x=feedRow(p)?.official_avg;return Number.isFinite(Number(x))&&Number(x)>0?Number(x):null}
function pricing(p){const ref=official(p),base=ref||p.pilotRef,src=feedRow(p);if(!Number.isFinite(base))return {ref:null,payout:null,sale:null,source:'Veri bekleniyor',official:false};const payout=Math.round((ref?base*(1+POLICY.farmerUplift):base)*100)/100,sale=Math.round((payout/(1-POLICY.platformShare))*100)/100;return {ref:base,payout,sale,source:ref?(src?.source==='hks'?'HKS':src?.source==='tobb'?'TOBB':'Resmi'):'Pilot referans',official:!!ref}}
function safe(t){return String(t).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function visual(p,wide=false){const hue=(PRODUCTS.indexOf(p)*37)%360,w=wide?1200:520,h=wide?700:420;const svg=`<svg xmlns='http://www.w3.org/2000/svg' width='${w}' height='${h}' viewBox='0 0 ${w} ${h}'><defs><linearGradient id='g' x1='0' y1='0' x2='1' y2='1'><stop stop-color='hsl(${hue} 45% 28%)'/><stop offset='1' stop-color='hsl(${(hue+55)%360} 52% 12%)'/></linearGradient><radialGradient id='r'><stop stop-color='rgba(255,255,255,.24)'/><stop offset='1' stop-color='rgba(255,255,255,0)'/></radialGradient></defs><rect width='100%' height='100%' fill='url(#g)'/><circle cx='${w*.82}' cy='${h*.18}' r='${h*.22}' fill='url(#r)'/><path d='M0 ${h*.62} Q ${w*.25} ${h*.46} ${w*.5} ${h*.63} T ${w} ${h*.58} V${h} H0Z' fill='rgba(38,120,66,.42)'/><path d='M0 ${h*.78} Q ${w*.33} ${h*.62} ${w*.66} ${h*.8} T ${w} ${h*.72} V${h} H0Z' fill='rgba(23,88,47,.55)'/><text x='50%' y='46%' text-anchor='middle' dominant-baseline='middle' font-size='${h*.33}'>${p.emoji}</text><rect x='${w*.05}' y='${h*.76}' width='${w*.9}' height='${h*.16}' rx='${h*.05}' fill='rgba(4,17,27,.66)'/><text x='${w*.09}' y='${h*.835}' font-family='Arial,sans-serif' font-size='${wide?38:26}' font-weight='700' fill='white'>${safe(p.name)}</text><text x='${w*.09}' y='${h*.885}' font-family='Arial,sans-serif' font-size='${wide?20:15}' fill='#9ff2ba'>${safe(p.cat)} • ${safe(p.location)}</text></svg>`;return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`}
function setView(view){$$('.app-view').forEach(v=>v.classList.toggle('active',v.dataset.view===view));$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===view));if(view==='live')setTimeout(initMap,60);if(view==='cart')renderCart()}
function visible(){return PRODUCTS.filter(p=>category==='all'||p.cat===category)}
function renderPicker(){const list=visible();$('#pickerCount').textContent=`${list.length} ürün`;$('#productPicker').innerHTML=list.map(p=>{const i=PRODUCTS.indexOf(p),pr=pricing(p);return `<button class="pick-card ${i===selected?'active':''}" data-product="${i}"><span class="pick-img" style="background-image:url('${visual(p)}')"></span><span><b>${p.name}</b><small>${p.location.split('/')[0].trim()} • ${pr.source}</small><strong>${pr.sale?kgMoney(pr.sale):'Fiyat bekleniyor'}</strong></span></button>`}).join('');$$('[data-product]').forEach(b=>b.addEventListener('click',()=>{selected=Number(b.dataset.product);renderPicker();renderDetail()}))}
function renderDetail(){const p=currentProduct(),pr=pricing(p);$('#detailPhoto').style.backgroundImage=`url('${visual(p,true)}')`;$('#detailFarm').textContent=p.farmer;$('#detailName').textContent=p.name;$('#detailLocation').textContent=p.location;$('#detailPrice').textContent=pr.sale?kgMoney(pr.sale):'Veri bekleniyor';$('#detailPayout').textContent=pr.payout?kgMoney(pr.payout):'—';$('#detailSource').textContent=pr.source;$('#detailFresh').textContent=p.fresh;$('#qtyValue').textContent=`${qty} kg`;$('#addCart').disabled=!pr.sale}
function renderCategories(){$$('#categoryTabs .chip').forEach(b=>b.classList.toggle('active',b.dataset.category===category))}
async function loadPrices(){const status=$('#priceFeedStatus');status.textContent='Resmi fiyat akışı yenileniyor…';try{const r=await fetch(`data/prices.json?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error();priceData=await r.json();const h=priceData.sources?.hks?.ok?'HKS ✓':'HKS —',t=priceData.sources?.tobb?.ok?'TOBB ✓':'TOBB —';status.textContent=`${h} • ${t} • ${priceData.generated_at?.slice(11,16)||'güncel'}`;$('#opsPriceState').textContent='Bağlı'}catch(e){status.textContent='Resmi akış alınamadı • pilot referans aktif';$('#opsPriceState').textContent='Pilot'}renderPicker();renderDetail();renderCart()}
function cartTotal(){return cart.reduce((s,x)=>{const pr=pricing(PRODUCTS[x.index]);return s+(pr.sale||0)*x.qty},0)}
function addCart(){const pr=pricing(currentProduct());if(!pr.sale)return;const found=cart.find(x=>x.index===selected);if(found)found.qty+=qty;else cart.push({index:selected,qty});payment=null;renderCart();updateCartBadge();$('#systemStatus').textContent=`${currentProduct().name} sepete eklendi`;setView('cart')}
function updateCartBadge(){const n=cart.reduce((s,x)=>s+x.qty,0);$('#cartCount').textContent=n;$('#cartCountTop').textContent=`${cart.length} çeşit`}
function renderCart(){const box=$('#cartList');if(!cart.length){box.innerHTML='<div class="empty-state"><b>Sepet boş</b><small>Pazar ekranından ürün seçip “Sepete ekle” butonunu kullanın.</small></div>';$('#cartTotal').textContent='0,00 ₺';$('#createPayment').disabled=true;$('#startPaidOrder').disabled=true;updateCartBadge();return}box.innerHTML=cart.map((x,n)=>{const p=PRODUCTS[x.index],pr=pricing(p),line=(pr.sale||0)*x.qty;return `<article class="cart-item"><span class="cart-img" style="background-image:url('${visual(p)}')"></span><div><b>${p.name}</b><small>${p.farmer} • ${p.location}</small><strong>${money(line)}</strong></div><div class="cart-qty"><button data-cart-minus="${n}">−</button><b>${x.qty} kg</b><button data-cart-plus="${n}">+</button><button class="remove" data-cart-remove="${n}">×</button></div></article>`}).join('');$('[id="cartTotal"]').textContent=money(cartTotal());$('#createPayment').disabled=false;$('#startPaidOrder').disabled=!payment;$$('[data-cart-minus]').forEach(b=>b.onclick=()=>{const i=+b.dataset.cartMinus;cart[i].qty=Math.max(1,cart[i].qty-1);payment=null;renderCart();updateCartBadge()});$$('[data-cart-plus]').forEach(b=>b.onclick=()=>{cart[+b.dataset.cartPlus].qty++;payment=null;renderCart();updateCartBadge()});$$('[data-cart-remove]').forEach(b=>b.onclick=()=>{cart.splice(+b.dataset.cartRemove,1);payment=null;renderCart();updateCartBadge()});updateCartBadge();renderPaymentState()}
function renderPaymentState(){const s=$('#paymentState');if(!payment){s.innerHTML='<span>ÖDEME DURUMU</span><b>Henüz oluşturulmadı</b><small>Bu MVP gerçek kart bilgisi toplamaz; gerçek ödeme kuruluşu entegrasyonu bağlanana kadar güvenli ödeme akışı pilot kaydı olarak çalışır.</small>';return}s.innerHTML=`<span>PİLOT GÜVENLİ ÖDEME KAYDI</span><b>${payment.id} • ${money(payment.amount)}</b><small>Ödeme bekleme kaydı oluşturuldu. Üretici hakedişi drone kalkışı doğrulanana kadar serbest bırakılmaz.</small>`}
function createPayment(){if(!cart.length)return;payment={id:`PAY-DEMO-${String(Date.now()).slice(-6)}`,amount:cartTotal(),created:new Date()};renderPaymentState();$('#startPaidOrder').disabled=false;$('#systemStatus').textContent='Güvenli ödeme kaydı hazır'}
function buildStageGrid(){$('#stageGrid').innerHTML=STAGES.map((s,i)=>`<div class="stage-dot" data-stage-dot="${i}"><span>${i+1}</span><small>${s[0]}</small></div>`).join('')}
function startPaidOrder(){if(!payment||!cart.length)return;clearInterval(stageTimer);stopRoute();const first=cart[0],p=PRODUCTS[first.index];activeOrder={id:`TT-${new Date().getFullYear()}-${String(Date.now()).slice(-5)}`,items:cart.map(x=>({...x})),product:p,total:payment.amount,payment:{...payment},started:new Date(),stage:0};stageIndex=0;$('#orderCode').textContent=activeOrder.id;$('#orderProduct').textContent=`${cart.length} çeşit • ${cart.reduce((s,x)=>s+x.qty,0)} kg`;$('#orderSummary').textContent=`${money(activeOrder.total)} • ödeme kaydı ${payment.id}`;$('#orderThumb').style.backgroundImage=`url('${visual(p)}')`;$('#opsOrderCount').textContent='1';$('#opsOrderState').textContent='Aktif';buildStageGrid();updateOrderStage(0);cart=[];payment=null;updateCartBadge();setView('order');stageTimer=setInterval(()=>{if(stageIndex>=STAGES.length-1){clearInterval(stageTimer);stageTimer=null;return}updateOrderStage(stageIndex+1)},6500)}
function orderKg(){return activeOrder?activeOrder.items.reduce((s,x)=>s+x.qty,0):0}
function stageText(i){const p=activeOrder?.product||currentProduct(),count=activeOrder?.items.length||1,kgs=orderKg()||qty;return [`${count} ürün çeşidi, toplam ${kgs} kg sipariş güvenli ödeme kaydıyla oluşturuldu.`,`Üretici görevleri ürün ve miktar bilgileriyle telefonlara gönderildi.`,`YZ operasyon merkezi çoklu ürün görevini, toplama sırasını ve drone rotasını hazırlıyor.`,`Üreticiler siparişe uygun ürünleri topluyor ve görsel onaya hazırlıyor.`,`Ürün fotoğrafları tüketici onayına sunuldu; paketler teslimata hazırlanıyor.`,`TT-D01 ilk üretici noktasından paketi aldı ve teslimat rotasına geçti.`,`Kalkış doğrulandı. Üretici hakedişi kayıtlı ödeme akışında serbest bırakıldı.`,`Teslimat tamamlandı. Drone operasyon merkezine geri dönüyor.`][i]}
function updateOrderStage(i){if(!activeOrder)return;stageIndex=i;activeOrder.stage=i;const s=STAGES[i];$('#orderTitle').textContent=s[0];$('#nowIcon').textContent=s[2];$('#nowTitle').textContent=s[1];$('#nowText').textContent=stageText(i);$('#orderProgress').style.width=`${((i+1)/STAGES.length)*100}%`;$$('[data-stage-dot]').forEach((el,n)=>{el.classList.toggle('done',n<i);el.classList.toggle('active',n===i)});$('#systemStatus').textContent=s[1];updateOps(i);updateLiveTelemetry(i);addOpsEvent(s[0],s[1]);if(i>=4)startRouteAnimation(i)}
function updateOps(i){$('#opsDroneState').textContent=i<4?'Hazır':i<7?'Görevde':'Dönüşte';$('#opsDroneDetail').textContent=i<4?'TT-D01 • merkez':i<6?'TT-D01 • üretici rotası':'TT-D01 • teslim rotası';$('#opsPayoutState').textContent=i>=6?'Serbest bırakıldı':'Beklemede'}
function addOpsEvent(title,text){const box=$('#opsTimeline');if(!box)return;const el=document.createElement('div');el.className='ops-event';el.innerHTML=`<time>${nowTime().slice(0,5)}</time><div><b>${title}</b><small>${text}</small></div>`;box.prepend(el);while(box.children.length>6)box.removeChild(box.lastChild)}
function initMap(){if(map){setTimeout(()=>map.invalidateSize(),60);return}const p=activeOrder?.product||currentProduct();map=L.map('routeMap',{zoomControl:false,attributionControl:true}).setView(p.center,14);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);setTimeout(()=>map.invalidateSize(),100)}
function routePoints(){const p=activeOrder?.product||currentProduct();return [p.center,p.farm,p.delivery,p.center]}
function startRouteAnimation(stage){initMap();if(!map||!activeOrder)return;const pts=routePoints();let segment=stage===4?0:stage<=6?1:2,from=pts[segment],to=pts[segment+1];if(routeLine)routeLine.remove();routeLine=L.polyline([from,to],{color:'#45dc86',weight:4,dashArray:'8 7',opacity:.9}).addTo(map);map.fitBounds(L.latLngBounds([from,to]).pad(.35));if(!droneMarker){droneMarker=L.marker(from,{icon:L.divIcon({className:'drone-marker',html:'<div class="drone-dot">✦</div>',iconSize:[30,30],iconAnchor:[15,15]})}).addTo(map)}routeProgress=0;clearInterval(routeTimer);routeTimer=setInterval(()=>{routeProgress=Math.min(1,routeProgress+.012);const lat=from[0]+(to[0]-from[0])*routeProgress,lng=from[1]+(to[1]-from[1])*routeProgress;droneMarker.setLatLng([lat,lng]);updateTelemetryValues(lat,lng,segment,routeProgress);if(routeProgress>=1)clearInterval(routeTimer)},220)}
function stopRoute(){clearInterval(routeTimer);routeTimer=null;routeProgress=0}
function updateTelemetryValues(lat,lng,segment,progress){const alt=segment===0?Math.round(18+progress*32):segment===1?52:Math.round(52-progress*26),spd=segment===1?46:36,batt=Math.max(48,100-Math.round((stageIndex*8)+(progress*5)));$('#altitude').textContent=`${alt} m`;$('#speed').textContent=`${spd} km/sa`;$('#battery').textContent=`${batt}%`;$('#distance').textContent=`${(1.8-progress*1.3).toFixed(1)} km`;$('#camAlt').textContent=`${alt} m`;$('#camSpeed').textContent=`${spd} km/sa`;$('#camGps').textContent=`${lat.toFixed(4)}, ${lng.toFixed(4)}`}
function updateLiveTelemetry(i){const on=i>=4;$('#routeStatusDot').classList.toggle('on',on);$('#mapEta').textContent=on?`${Math.max(2,10-i)} dk`:'—';$('#routeStatusTitle').textContent=on?STAGES[i][1]:'Rota bekleniyor';$('#routeStatusText').textContent=on?stageText(i):'Sipariş verildiğinde operasyon merkezi rotayı burada gösterecek.';$('#cameraTitle').textContent=on?'TT-D01 saha kamerası':'Kamera bağlantısı hazır';$('#cameraText').textContent=on?'Drone görev akışıyla birlikte kamera ve telemetri aynı sipariş kimliğine bağlı izleniyor.':'Gerçek drone video URL\'si tanımlandığında bu alan doğrudan canlı yayına geçer; şu an pilot saha görünümü kullanılıyor.'}
function setupVideoHook(){const url=window.DRONE_VIDEO_URL,v=$('#droneVideo'),fb=$('#cameraFallback');if(url){v.src=url;v.style.display='block';fb.style.display='none';$('#liveModeLabel').textContent='Canlı kamera'}else{$('#liveModeLabel').textContent='Pilot simülasyon'}}
function updateClock(){$('#camTime').textContent=nowTime()}
function setupTelemetryHook(){const wsUrl=window.DRONE_TELEMETRY_WS;if(!wsUrl)return;try{const ws=new WebSocket(wsUrl);ws.onopen=()=>{$('#liveModeLabel').textContent='Canlı telemetri'};ws.onmessage=e=>{try{const d=JSON.parse(e.data);if(Number.isFinite(d.lat)&&Number.isFinite(d.lng)){initMap();if(!droneMarker)droneMarker=L.marker([d.lat,d.lng]).addTo(map);else droneMarker.setLatLng([d.lat,d.lng]);$('#camGps').textContent=`${d.lat.toFixed(4)}, ${d.lng.toFixed(4)}`}if(Number.isFinite(d.altitude)){const v=`${Math.round(d.altitude)} m`;$('#altitude').textContent=v;$('#camAlt').textContent=v}if(Number.isFinite(d.speed)){const v=`${Math.round(d.speed)} km/sa`;$('#speed').textContent=v;$('#camSpeed').textContent=v}if(Number.isFinite(d.battery))$('#battery').textContent=`${Math.round(d.battery)}%`;}catch(_){}}}catch(_){}}
function renderProjectTabs(){$$('[data-project-pane]').forEach(b=>b.onclick=()=>{$$('[data-project-pane]').forEach(x=>x.classList.toggle('active',x===b));$$('[data-project-content]').forEach(x=>x.classList.toggle('active',x.dataset.projectContent===b.dataset.projectPane))})}
$$('.bottom-nav button').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.nav)));$$('#categoryTabs .chip').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.category;const list=visible();if(!list.includes(currentProduct()))selected=PRODUCTS.indexOf(list[0]||PRODUCTS[0]);renderCategories();renderPicker();renderDetail()}));$('#qtyMinus').addEventListener('click',()=>{qty=Math.max(1,qty-1);renderDetail()});$('#qtyPlus').addEventListener('click',()=>{qty=Math.min(50,qty+1);renderDetail()});$('#addCart').addEventListener('click',addCart);$('#createPayment').addEventListener('click',createPayment);$('#startPaidOrder').addEventListener('click',startPaidOrder);$('#refreshPrices').addEventListener('click',loadPrices);$('#openLiveFromOrder').addEventListener('click',()=>setView('live'));$$('[data-live-pane]').forEach(b=>b.addEventListener('click',()=>{$$('[data-live-pane]').forEach(x=>x.classList.toggle('active',x===b));$$('[data-live-content]').forEach(x=>x.classList.toggle('active',x.dataset.liveContent===b.dataset.livePane));if(b.dataset.livePane==='map')setTimeout(initMap,50)}));renderProjectTabs();renderCategories();renderPicker();renderDetail();buildStageGrid();renderCart();renderPaymentState();setupVideoHook();setupTelemetryHook();loadPrices();setInterval(updateClock,1000);updateClock();